# Generated by Django 4.1.7 on 2024-03-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofmaterial', models.CharField(default='None', max_length=150)),
                ('numberofmaterial', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
