# Generated by Django 4.1.7 on 2024-03-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(default='مدیریت', max_length=150)),
                ('melicod', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='jobsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(default='مدیر', max_length=150)),
                ('employee', models.CharField(default='مدیریت', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='workmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(default='تزریقات', max_length=150)),
                ('detalework', models.CharField(default='تزریقات', max_length=150)),
                ('person', models.CharField(default='من', max_length=150)),
                ('time', models.CharField(default='امروز', max_length=50)),
                ('cast', models.CharField(default='0', max_length=150)),
            ],
        ),
    ]
