# Generated by Django 4.1.7 on 2024-03-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accuntmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('melicode', models.CharField(default='0', max_length=10)),
                ('phonnumber', models.CharField(default='0', max_length=11)),
                ('berthday', models.CharField(max_length=100)),
                ('pasword', models.CharField(max_length=100)),
                ('level', models.CharField(default='دسترسی معمولی', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='savecodphon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('melicode', models.CharField(default='0', max_length=20)),
                ('phonnumber', models.CharField(default='0', max_length=20)),
                ('berthday', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('expaiercode', models.CharField(max_length=20)),
            ],
        ),
    ]
